### ISSUE TITLE
Vim (but not nvim) hijacking <C-W> when in terminal buffer

### ISSUE THREAD

**Issue by yogeshdhamija** [ydhamija96/config#3]
## Problem

In vim, when in a terminal buffer in insert/terminal mode, pressing `<C-W>` engages the vim window mappings, thus not allowing you to use the same keymap specified in the `~/.zshrc` to complete word. 

This does not occur in nvim, where the `<C-W>` is successfully captured within the terminal buffer, and a `<C-\><C-n>` must be done to have the keys parsed as a window mapping.

## Conditions

Confirmed to occur on Mac OS in iTerm2.

**Comment by ghost** [comment]
Outside of this repository, I've noticed, that vim keybindings will conflict with ones the shell uses. I can't imagine a way around this, without us changing our keys, but there's always a risk a program will have conflicting shortcuts.

I think the issue lies within vim, in that perhaps an option should be given (a `set` option?) to enable or disable vim's own, else rely on the shell's. Unless one already exists.

I've not used `zsh` in a _very_ long time, so I've no idea if there's a setting somehow allowing you to disable or force shell's own shortcuts in certain cases.

Just a thought, but from looking at your `.vimrc` file, it looks like you're using a lot of plugins and other things, so have you checked to see if the problem still occurs even without loading up that file? I think `vim -u NONE` is the command for this. I can't imagine its that, but by process of elimination...

**Comment by yogeshdhamija** [comment]
Ah I hadn't seen your reply! I've found that this is simply a case of vim and neovim treating terminal buffers differently. This is independent of any configuration. In vim, pressing `<C-W>` in a terminal buffer is treated as vim keybinding, while neovim passes that on to the terminal buffer. 

I don't think it's feasible to apply configuration on top of either system to enforce that they behave the same way, and so I'm closing this issue.
